config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index', as: 'home'
  root 'home#credit', as: 'credit'
  root 'home#partner', as: 'partner'
  root 'home#condition', as: 'condition'

  # Routes for planets
  resources :planets

  # Routes for grades
  resources :grades

  # Routes for astronauts
  resources :astronauts

  # Routes for expeditions
  resources :expeditions

  # Routes for reports
  resources :reports

  # Routes for reports
  resources :partner

  # Routes for reports
  resources :condition

  # Routes for reports
  resources :credit

end

app/models/astronaut.rb
# frozen_string_literal: true

# Astronaut
class Astronaut < ApplicationRecord
  belongs_to :grade
  belongs_to :planet
  has_many :expedition_astronauts
  has_many :expeditions, through: :expedition_astronauts
  has_many :reports
end

app/controllers/astronauts_controller.rb
# frozen_string_literal: true

# Astronaut Controller
class AstronautsController < ApplicationController
  before_action :fetch_astronaut, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @astronauts = Astronaut.includes(:grade, :planet)
  end

  def create
    @astronaut = Astronaut.new astronaut_parameters
    if @astronaut.save
      flash[:success] = 'Astronaut "' + astronaut_parameters[:name] + '" created !'

      redirect_to astronauts_url
    else
      render action: 'new'
    end
  end

  def new
    @astronaut = Astronaut.new
  end

  def show
    # @astronaut fetched from :fetch_astronaut
  end

  def update
    if @astronaut.update_attributes astronaut_parameters
      flash[:success] = 'Astronaut #' + astronaut_parameters[:name] + ' updated !'

      redirect_to astronauts_url
    else
      render action: :edit
    end
  end

  def edit
    # @astronaut fetched from :fetch_astronaut
  end

  def destroy
    @astronaut.destroy

    flash[:success] = 'Astronaut destroyed with success !'
    redirect_to astronauts_url
  end

  private

  def fetch_astronaut
    @astronaut = Astronaut.find(params[:id])
  end

  def astronaut_parameters
    params.require(:astronaut).permit(:name, :mail, :grade_id, :planet_id)
  end

end

app/helpers/astronauts_helper.rb
module AstronautsHelper
  def grade_user(name, grade)
    raw "#{grade} #{name} "
  end
end

app/views/astronauts/_astronaut_list.html.erb
<% if astronauts.any? %>
  <% astronauts.each do |m| %>
    <%= link_to m.name, m %>
  <% end %>
<% else %>
  &empty;
<% end %>

app/views/astronauts/_form.html.erb
<% if @astronaut.errors.any? %>
  <div class="callout callout-danger">
    <h4>Error during the object save</h4>

    <p>There is one or more errors for this object :</p>
    <ul>
      <% @astronaut.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for(@astronaut, :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="well">
    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :name %></label>
      <div class="col-sm-5">
        <%= f.text_field :name, :required => true, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :mail %></label>
      <div class="col-sm-5">
        <%= f.text_field :mail, :required => true, :class => 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :grade %></label>
      <div class="col-sm-5">
        <%= f.association :grade, :required => true, prompt: 'Choose your grade', label: false,
                          input_html: { :class => 'form-control' } %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :planet %></label>
      <div class="col-sm-5">
        <%= f.association :planet, :required => true, prompt: 'Choose your planet', label: false,
                          input_html: { :class => 'form-control' } %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/astronauts/edit.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= astronauts_path %>"><span class="glyphicon glyphicon-chevron-left"></span>
    Retour</a>
  <h3>Edit astronaut <%= @astronaut.name %></h3>
</div>

<%= render 'form' %>

app/views/astronauts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Astronaut</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @astronauts.any? %>
      <table class="table" id="dataTable" style="width: 100%;">
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Grade</th>
          <th>Planet</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @astronauts.each do |astronaut| %>
          <tr>
            <td><%= astronaut.id %></td>
            <td><%= astronaut.name %></td>
            <td>
              <% if astronaut.grade.nil? %>
                &empty;
              <% else %>
                <%= astronaut.grade.name.nil? ? '&empty;' : astronaut.grade.name %>
              <% end %>
            </td>
            <td>
              <% if astronaut.planet.nil? %>
                &empty;
              <% else %>
                <%= astronaut.planet.name.nil? ? '&empty;' : astronaut.planet.name %>
              <% end %>
            </td>
            <td>
              <div class="btn-group pull-right">
                <a href="<%= astronaut_path astronaut %>" class="btn btn-success">
                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Details
                </a>
                <% if user_signed_in? %>
                  <a href="<%= edit_astronaut_path astronaut %>" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                  </a>
                  <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete'),
                              astronaut,
                              method: :delete,
                              data: {
                                  confirm: 'Are you sure you want to delete this astronaut ?'
                              },
                              class: 'btn btn-danger'
                  %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
        <tfoot>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Grade</th>
          <th>Planet</th>
          <th class="disabled">Actions</th>
        </tr>
        </tfoot>
      </table>
    <% else %>
      <div class="alert alert-info">
        No astronaut created for the moment.
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-6">
      <a href="<%= new_astronaut_path %>" type="button" class="btn btn-default pull-right">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add an astronaut
      </a>
    </div>
  </div>
<% end %>

app/views/astronauts/new.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= astronauts_path %>"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
  <h3>New astronaut</h3>
</div>

<%= render 'form' %>

app/views/astronauts/show.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= astronauts_path %>"><span class="glyphicon glyphicon-chevron-left"></span>
    Back</a>
  <h3>
    <% if @astronaut.grade.nil? %>
      <%= @astronaut.name %>
    <% else %>
      <%= image_tag("icon/icons8-caporal-50.png", :alt => "grade major") %>
      <%= grade_user(@astronaut.name, @astronaut.grade.name) %>
    <% end %>
  </h3>
</div>

<div class="well">
  <div class="row">

    <div class="col-md-12">
      <label class="col-sm-2">Name</label>
      <span><%= @astronaut.name.nil? ? '&empty;' : @astronaut.name %></span>
    </div>

    <div class="col-md-12">
      <label class="col-sm-2">Mail</label>
      <span><%= @astronaut.mail.nil? ? '&empty;' : @astronaut.mail %></span>
    </div>

    <div class="col-md-12">
      <label class="col-sm-2">Planet</label>
      <span><%= @astronaut.planet.nil? ? '&empty;' : @astronaut.planet.name %></span>
    </div>

  </div>
</div>