config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index', as: 'home'
  root 'home#credit', as: 'credit'
  root 'home#partner', as: 'partner'
  root 'home#condition', as: 'condition'

  # Routes for planets
  resources :planets

  # Routes for grades
  resources :grades

  # Routes for astronauts
  resources :astronauts

  # Routes for expeditions
  resources :expeditions

  # Routes for reports
  resources :reports

  # Routes for reports
  resources :partner

  # Routes for reports
  resources :condition

  # Routes for reports
  resources :credit

end

app/models/planet.rb
# frozen_string_literal: true

# Planet
class Planet < ApplicationRecord
  has_many :astronaut
  has_many :expeditions
  has_one_attached :photo
end

app/controllers/planets_controller.rb
# frozen_string_literal: true

# Planet Controller
class PlanetsController < ApplicationController
  before_action :fetch_planet, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @planets = Planet.all
  end

  def create
    @planet = Planet.new planet_attributes
    if @planet.save
      flash[:success] = 'Planet "' + planet_attributes[:name] + '" created !'

      redirect_to planets_url
    else
      render action: 'new'
    end
  end

  def new
    @planet = Planet.new
  end

  def edit
    # @planet fetched from :fetch_planet
  end

  def show
    # @planet fetched from :fetch_planet
  end

  def update
    if @planet.update_attributes planet_attributes
      flash[:success] = 'Planet #' + planet_attributes[:name] + ' updated !'

      redirect_to planets_url
    else
      render action: :edit
    end
  end

  def destroy
    @planet.destroy

    flash[:success] = 'Planet destroyed with success!'
    redirect_to planets_url
  end

  private

  def planet_attributes
    params.require(:planet).permit(:name, :description, :photo)
  end

  def fetch_planet
    @planet = Planet.find(params[:id])
  end
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/_form.html.erb
<% if @planet.errors.any? %>
  <div class="callout callout-danger">
    <h4>Error during the object save</h4>

    <p>There is one or more errors for this object :</p>
    <ul>
      <% @planet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @planet, :html => { :class => 'form-horizontal'}) do |f| %>
    <div class="well">
      <div class="form-group">
        <label class="col-sm-2 control-label"><%= f.label :name %></label>
        <div class="col-sm-5">
          <%= f.text_field :name, :required => true, :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"><%= f.label :description %></label>
        <div class="col-sm-5">
          <%= f.text_area :description, :required => true, :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label for="photo" class="col-sm-2 control-label"><%= f.label :photo %></label>
        <div class="col-sm-5">
          <%= f.file_field :photo, :required => true, :class => 'form-control', :id => 'photo' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
<% end %>

app/views/planets/edit.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= planets_path %>"><span class="glyphicon glyphicon-chevron-left"></span>
    Back</a>
  <h3>Edit the planet <%= @planet.name %></h3>
</div>

<%= render 'form' %>

app/views/planets/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Planets</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @planets.any? %>
      <table class="table" id="dataTable" style="width: 100%;">
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>
            <div class="col-md-2 col-md-offset-10">Actions</div>
          </th>
        </tr>
        </thead>
        <tbody>
        <% @planets.each do |planet| %>
          <tr>
            <td><%= planet.id %></td>
            <td><%= planet.name %></td>
            <td>
              <div class="btn-group pull-right">
                <a href="<%= planet_path planet %>" class="btn btn-success">
                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Details
                </a>
                <% if user_signed_in? %>
                <a href="<%= edit_planet_path planet %>" class="btn btn-info">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                </a>
                <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete'),
                            planet,
                            method: :delete,
                            data: {
                                confirm: 'Are you sure you want to delete this planet ?'
                            },
                            class: 'btn btn-danger'
                %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
        <tfoot>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th class="disabled">Actions</th>
        </tr>
        </tfoot>
      </table>
    <% else %>
      <div class="alert alert-info" role="alert">
        No planet created for the moment.
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
<div class="row">
  <div class="col-md-6 col-md-offset-6">
    <a href="<%= new_planet_path %>" type="button" class="btn btn-default pull-right">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a planet
    </a>
  </div>
</div>
<% end %>

app/views/planets/new.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= planets_path %>"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
  <h3>New planet</h3>
</div>

<%= render 'form' %>

app/views/planets/show.html.erb
<div class="nav-header">
  <a class="btn btn-primary btn-sm" href="<%= planets_path %>"><span class="glyphicon glyphicon-chevron-left"></span>
    Back</a>
  <h3>Planet <%= @planet.name %></h3>
</div>

<div class="well">
  <div class="row">
    <div class="col-md-12">
      <label class="col-sm-2">Name</label>
      <span><%= @planet.name %></span>
    </div>

    <div class="col-md-12">
      <label class="col-sm-2">Description</label>
      <span><%= @planet.description %></span>
    </div>

    <div class="col-md-12">
      <% photo = @planet.photo %>
    <% if photo.nil? %>
        <span>No photo</span>
    <% else %>
        <label class="col-sm-2">Image</label>
        <img class="planet-photo" src="<%= url_for(photo) %>" alt="Planet Photo">
    <% end %>
    </div>

    <div class="col-md-12">
      <label class="col-sm-2">Created at</label>
      <span><%= @planet.created_at.strftime('%d/%m/%Y') %></span>
    </div>

  </div>
</div>