config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index', as: 'home'
  root 'home#credit', as: 'credit'
  root 'home#partner', as: 'partner'
  root 'home#condition', as: 'condition'

  # Routes for planets
  resources :planets

  # Routes for grades
  resources :grades

  # Routes for astronauts
  resources :astronauts

  # Routes for expeditions
  resources :expeditions

  # Routes for reports
  resources :reports

  # Routes for reports
  resources :partner

  # Routes for reports
  resources :condition

  # Routes for reports
  resources :credit

end

app/models/report.rb
# frozen_string_literal: true

# Report
class Report < ApplicationRecord
  belongs_to :astronaut, optional: true
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# ReportsController
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @reports = Report.all
  end

  def create
    @report = Report.new(report_params)
    report_params.inspect
    if @report.save
      flash[:success] = 'Report "' + report_params[:name] + '" created !'

      redirect_to reports_url
    else
      render :new
    end
  end

  def new
    @report = Report.new
  end

  def edit
    # @report fetched from :set_report
  end

  def show
    # @report fetched from :set_report
  end

  def update
    if @report.update(report_params)
      flash[:success] = 'Report "' + report_params[:name] + '" updated !'
      redirect_to reports_url
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    flash[:success] = 'Report destroyed with success !'

    redirect_to reports_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:name, :description, :astronaut_id)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(report) do |form| %>
  <%= form.error_notification %>
  <%= form.error_notification message: form.object.errors[:base].to_sentence if form.object.errors[:base].present? %>

  <div class="form-group">
    <%= form.input :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.input :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.association :astronaut, class: 'form-control' %>
  </div>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/reports/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edit a report</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form', report: @report %>
  </div>
</div>

app/views/reports/index.html.erb
<h1>Reports</h1>

<div class="row">
  <div class="col-md-12">
    <% if @reports.any? %>
      <table class="table" id="dataTable" style="width: 100%;">
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Description</th>
          <th>Astronaut</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report.id %></td>
            <td><%= report.name %></td>
            <td><%= report.description %></td>
            <td><%= report.astronaut.nil? ? 'Non défini' : report.astronaut.name %></td>
            <td>
              <div class="btn-group pull-right" role="group">
                <a href="<%= report_path report %>" class="btn btn-success">
                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Details
                </a>

                <% if user_signed_in? %>
                  <a href="<%= edit_report_path report %>" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                  </a>

                  <%= link_to raw('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete'),
                              report,
                              method: :delete,
                              data: {
                                  confirm: 'Are you sure you want to delete this report ?'
                              },
                              class: 'btn btn-danger'
                  %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
        <tfoot>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Description</th>
          <th>Astronaut</th>
          <th class="disabled">Actions</th>
        </tr>
        </tfoot>

      </table>
    <% else %>
      <div class="alert alert-info" role="alert">
        No report for the moment.
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-6">
      <%= link_to(new_report_path, class: 'btn btn-default pull-right', title: 'Ajouter un rapport') do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a report
      <% end %>
    </div>
  </div>
<% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

app/views/reports/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Name : <%= @report.name %></h1>
    <p>Description : <%= @report.description %></p>
    <p>Astronaut : <%= @report.astronaut.nil? ? '&empty;' : @report.astronaut.name %></p>
  </div>
</div>