config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index', as: 'home'
  root 'home#credit', as: 'credit'
  root 'home#partner', as: 'partner'
  root 'home#condition', as: 'condition'

  # Routes for planets
  resources :planets

  # Routes for grades
  resources :grades

  # Routes for astronauts
  resources :astronauts

  # Routes for expeditions
  resources :expeditions

  # Routes for reports
  resources :reports

  # Routes for reports
  resources :partner

  # Routes for reports
  resources :condition

  # Routes for reports
  resources :credit

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astronaut.rb
# frozen_string_literal: true

# Astronaut
class Astronaut < ApplicationRecord
  belongs_to :grade
  belongs_to :planet
  has_many :expedition_astronauts
  has_many :expeditions, through: :expedition_astronauts
  has_many :reports
end

app/models/expedition.rb
# frozen_string_literal: true

# Expedition
class Expedition < ApplicationRecord
  belongs_to :planet
  has_many :expedition_astronauts
  has_many :astronauts, through: :expedition_astronauts
  scope :last_opened, -> { where('end_date > ?', DateTime.now).order(created_at: :desc).last }
end

app/models/expedition_astronaut.rb
# frozen_string_literal: true

# ExpeditionAstronaut
class ExpeditionAstronaut < ApplicationRecord
  belongs_to :expedition
  belongs_to :astronaut
end

app/models/grade.rb
# frozen_string_literal: true

# Grade
class Grade < ApplicationRecord
  has_many :astronaut
end

app/models/planet.rb
# frozen_string_literal: true

# Planet
class Planet < ApplicationRecord
  has_many :astronaut
  has_many :expeditions
  has_one_attached :photo
end

app/models/report.rb
# frozen_string_literal: true

# Report
class Report < ApplicationRecord
  belongs_to :astronaut, optional: true
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/condition_controller.rb
# frozen_string_literal: true

# ConditionController
class ConditionController < ApplicationController
  def index
  end
end

app/controllers/credit_controller.rb
# frozen_string_literal: true

# CreditController
class CreditController < ApplicationController
  def index
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @grades = Grade.all
  end

  def create
    @grade = Grade.new grade_params
    if @grade.save
      flash[:success] = 'Grade "' + grade_params[:name] + '" created !'

      redirect_to @grade
    else
      render 'new'
    end
  end

  def new
    @grade = Grade.new
  end

  def edit
    # @grade fetched from :set_grade
  end

  def show
    # @grade fetched from :set_grade
  end

  def update
    if @grade.update grade_params
      flash[:success] = 'Grade "' + grade_params[:name] + '" updated !'

      redirect_to grades_url
    else
      render 'edit'
    end
  end

  def destroy
    @grade.destroy

    flash[:success] = 'Grade destroyed with success !'

    redirect_to grades_url
  end

  private

  def grade_params
    params.require(:grade).permit(:name, :alias, :description)
  end

  def set_grade
    @grade = Grade.find(params[:id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# HomeController
class HomeController < ApplicationController
  def index
    @expedition = Expedition.last_opened
  end
end

app/controllers/partner_controller.rb
# frozen_string_literal: true

# PartnerController
class PartnerController < ApplicationController
  def index
  end
end

app/controllers/planets_controller.rb
# frozen_string_literal: true

# Planet Controller
class PlanetsController < ApplicationController
  before_action :fetch_planet, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @planets = Planet.all
  end

  def create
    @planet = Planet.new planet_attributes
    if @planet.save
      flash[:success] = 'Planet "' + planet_attributes[:name] + '" created !'

      redirect_to planets_url
    else
      render action: 'new'
    end
  end

  def new
    @planet = Planet.new
  end

  def edit
    # @planet fetched from :fetch_planet
  end

  def show
    # @planet fetched from :fetch_planet
  end

  def update
    if @planet.update_attributes planet_attributes
      flash[:success] = 'Planet #' + planet_attributes[:name] + ' updated !'

      redirect_to planets_url
    else
      render action: :edit
    end
  end

  def destroy
    @planet.destroy

    flash[:success] = 'Planet destroyed with success!'
    redirect_to planets_url
  end

  private

  def planet_attributes
    params.require(:planet).permit(:name, :description, :photo)
  end

  def fetch_planet
    @planet = Planet.find(params[:id])
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# ReportsController
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit update destroy]

  def index
    @reports = Report.all
  end

  def create
    @report = Report.new(report_params)
    report_params.inspect
    if @report.save
      flash[:success] = 'Report "' + report_params[:name] + '" created !'

      redirect_to reports_url
    else
      render :new
    end
  end

  def new
    @report = Report.new
  end

  def edit
    # @report fetched from :set_report
  end

  def show
    # @report fetched from :set_report
  end

  def update
    if @report.update(report_params)
      flash[:success] = 'Report "' + report_params[:name] + '" updated !'
      redirect_to reports_url
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    flash[:success] = 'Report destroyed with success !'

    redirect_to reports_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:name, :description, :astronaut_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astronauts_helper.rb
module AstronautsHelper
  def grade_user(name, grade)
    raw "#{grade} #{name} "
  end
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="icon" type="image/png" href="assets/icon/icons8-planet-48.png">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <title>RubyPlanet</title>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "RubyPlanet", home_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="<%= 'active' if params[:controller] == 'home' %>">
          <%= link_to "Home", home_path %>
        </li>

        <li class="<%= 'active' if params[:controller] == 'planets' %>">
          <%= link_to "Planets", planets_path %>
        </li>

        <li class="<%= 'active' if params[:controller] == 'grades' %>">
          <%= link_to "Grades", grades_path %>
        </li>

        <li class="<%= 'active' if params[:controller] == 'astronauts' %>">
          <%= link_to "Astronauts", astronauts_path %>
        </li>

        <li class="<%= 'active' if params[:controller] == 'reports' %>">
          <%= link_to "Reports", reports_path %>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Disconnect',
                          destroy_user_session_path,
                          method: :delete
          %></li>
          <li>
            <p class="navbar-text"><%= current_user.email %></p>
          </li>
        <% else %>
          <li><%= link_to 'Connect', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>
</div> <!-- /.container -->

<div class="footer">
  <p>
    <%= link_to 'Partner', partner_path %>
    <%= link_to 'Credit', credit_path %>
    <%= link_to 'Term&Condition', condition_path %>
  </p>
</div>
</body>
</html>